name: build-freds-openwrt-x86-64

on: 
  push

permissions:
  contents: read

jobs:
  build:
    name: Build Fred's OpenWrt
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: openwrt/openwrt
          ref: v22.03.3

      - name: Setup build system
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt update
          sudo apt -y install build-essential clang flex bison g++ gawk gcc-multilib gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget

      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Run customization script
        env: 
            REPO_URL: https://github.com/fredtanxo/openwrt-build
            REPO_BRANCH: main
        run: |
          git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt-build
          [ -e openwrt-build/customize.sh ] && chmod +x openwrt-build/customize.sh && ./openwrt-build/customize.sh

      - name: Append configuration changes
        run: |
          [ -e openwrt-build/diffconfig ] && cp openwrt-build/diffconfig .config

      - name: Generate configuration
        run: make defconfig

      - name: Download dependencies
        run: make -j $(($(nproc)+1)) download

      - name: Build firmware image
        run: make -j $(($(nproc)+1))

      - name : Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: OpenWrt
          path: bin
