name: build-freds-openwrt-x86-64

on:
  push

permissions:
  contents: read

jobs:
  build:
    name: Build Fred's OpenWrt
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: openwrt-build

      - name: Prepare source code
        run: |
          git clone https://git.openwrt.org/openwrt/openwrt.git
          echo "VERSION=$(cat ./openwrt-build/version)" >> $GITHUB_ENV
          cd openwrt
          git checkout $VERSION
          echo "COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Setup build system
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          echo 'APT::Get::Always-Include-Phased-Updates "false";' | sudo tee /etc/apt/apt.conf.d/99-phased-updates
          sudo apt-get update
          sudo apt-get -y upgrade
          sudo apt-get -y install build-essential clang flex bison g++ gawk gcc-multilib gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget

      - name: Run customization script
        run: |
          [ -e ./openwrt-build/customize.sh ] && chmod +x ./openwrt-build/customize.sh && ./openwrt-build/customize.sh && echo "Done"

      - name: Update and install feeds
        working-directory: openwrt
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Append configuration changes
        run: |
          [ -e ./openwrt-build/diffconfig ] && cp ./openwrt-build/diffconfig ./openwrt/.config && echo "Done"

      - name: Generate configuration
        working-directory: openwrt
        run: make defconfig

      - name: Download dependencies
        working-directory: openwrt
        run: make -j $(($(nproc)+1)) download

      - name: Build firmware image
        working-directory: openwrt
        run: make -j $(($(nproc)+1))

      - name : Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: openwrt-${{ env.VERSION }}-${{ env.COMMIT }}
          path: openwrt/bin/targets
